version: '3.9'

services:
  resource-db:
    image: postgres:17-alpine3.21
    container_name: resource-db
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: ${RESOURCE_POSTGRES_PASSWORD}
      POSTGRES_USER: ${RESOURCE_POSTGRES_USER}
      POSTGRES_DB: ${RESOURCE_POSTGRES_DB}
    volumes:
      - ./init-scripts/resource-db/init.sql:/docker-entrypoint-initdb.d/init.sql
  song-db:
    image: postgres:17-alpine3.21
    container_name: song-db
    restart: always
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: ${SONG_POSTGRES_PASSWORD}
      POSTGRES_USER: ${SONG_POSTGRES_USER}
      POSTGRES_DB: ${SONG_POSTGRES_DB}
    volumes:
      - ./init-scripts/song-db/init.sql:/docker-entrypoint-initdb.d/init.sql
  resource-service:
    build: ./resource-service/.
    container_name: resource-service
    depends_on:
      - resource-db
      - service-registry
      - song-service
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: ${RESOURCE_SERVER_PORT}
      POSTGRES_PASSWORD: ${RESOURCE_POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${RESOURCE_POSTGRES_USER}
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      POSTGRES_DB: ${RESOURCE_POSTGRES_DB}
      JPA_GENERATED_DDL: ${RESOURCE_JPA_GENERATED_DDL}
      JPA_HIBERNATE_DDL_AUTO: ${RESOURCE_JPA_HIBERNATE_DDL_AUTO}
      SONG_SERVICE_NAME: ${SONG_SERVICE_NAME}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
  song-service:
    build: ./song-service/.
    deploy:
      replicas: 2
    depends_on:
      - song-db
      - service-registry
    environment:
      SERVER_PORT: ${SONG_SERVER_PORT}
      POSTGRES_PASSWORD: ${SONG_POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${SONG_POSTGRES_USER}
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      POSTGRES_DB: ${SONG_POSTGRES_DB}
      JPA_GENERATED_DDL: ${SONG_JPA_GENERATED_DDL}
      JPA_HIBERNATE_DDL_AUTO: ${SONG_JPA_HIBERNATE_DDL_AUTO}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}
  service-registry:
    build: ./service-registry/.
    container_name: service-registry
    restart: always
    ports:
      - "8761:8761"
  api-gateway:
    build: ./api-gateway/.
    depends_on:
      - service-registry
      - song-db
      - resource-service
    container_name: api-gateway
    restart: always
    ports:
      - "8888:8888"
    environment:
      SERVER_PORT: ${GATEWAY_SERVER_PORT}
      EUREKA_SERVER_URL: ${EUREKA_SERVER_URL}